[Server]
    Environment = "development"
    Host        = "localhost"
    Port        = 9000
    Debug       = false
    Timeout     = "10s"

[Database]
    Host        = "localhost"
    Driver      = "mysql"
    Username    = "root"
    Password    = ""
    Name        = "exercise-1"
